disabled_rules:
  - line_length
  - identifier_name
  - nesting  # Allow deeply nested enums for namespacing
  - type_name
  - explicit_enum_raw_value
  - file_length
  - function_body_length
  - type_body_length  # Test files with comprehensive tests can be large
  - redundant_discardable_let  # Preserve 'let _ =' in result builder contexts (required for Swift 6.0+)
  - opening_brace  # Handled by swift-format
  - trailing_comma  # Handled by swift-format
  - trailing_whitespace  # Handled by swift-format
  - orphaned_doc_comment
  - inclusive_language
  - redundant_string_enum_value
  - todo
  - comment_spacing
  - force_try  # Acceptable in live test implementations
  - for_where  # Intentional control flow clarity
  - is_disjoint  # Style preference

opt_in_rules:
  - empty_count
  - sorted_imports
  - force_cast
  - closure_spacing
  - operator_usage_whitespace
  - private_outlet
  - redundant_nil_coalescing
  - empty_string
  - literal_expression_end_indentation
  - single_test_class
  - sorted_first_last
  - vertical_whitespace
  - strict_fileprivate
  - legacy_random
  - no_extension_access_modifier
  - colon
  - trailing_comma
  
included:
  - Package.swift
  - Sources
  - Tests

excluded:
  - Carthage
  - Pods
  - fastlane
  - build
  - .build

analyzer_rules:
  - unused_import

colon:
  apply_to_dictionaries: true

vertical_whitespace:
  max_empty_lines: 1
